os: linux
dist: xenial
language: python
python: 3.8.5

jobs:
  include:
    - name: Linux tests

    - name: MacOS tests
      os: osx
      osx_image: xcode12
      language: shell
      addons:
        homebrew:
          packages:
            - python@3.8

    - name: Documentation build
      install:
        - pip install .[docs]
      script:
        - sphinx-build docs docs/_build
      addons:
        apt:
          packages:
            - pandoc

install:
  - pip install .[test]

script:
  - pytest tests
