channels:
- http://ssb.stsci.edu/astroconda
- conda-forge
- defaults
dependencies:
- healpy>=1.10
- jwxml>=0.3.0
- matplotlib>=3.0.0
- python>=3.6
- sphinx>=2.1
- yaml>=0.1.7
- pip:
    - astropy>=3.2.1
    - numpy>=1.16
    - jwst
    - pysiaf>0.3.0
    - pytest>=3.8.1
    - scipy>=1.1.0
