channels:
- http://ssb.stsci.edu/astroconda
- conda-forge
- defaults
dependencies:
- asdf>=2.1.0.dev1+ga161518
- astropy>=3.2.1
- crds>=7.4.1
- gwcs>=0.10a.dev21+g75e92da
- healpy>=1.10
- jwxml>=0.3.0
- matplotlib>=3.0.0
- numpy>=1.16
- photutils>=0.6
- pip>=18.0
- pytest>=3.8.1
- python>=3.6,<3.7
- pyyaml>=5.1.1
- scipy>=1.1.0
- sphinx>=2.1
- yaml>=0.1.7
- pip:
    - git+https://github.com/spacetelescope/jwst@0.13.8
    - pysiaf>0.3.0